export {default as Home} from './Home'
export {default as About} from './About'
export {default as Contact} from './Contact'
export {default as Product} from './Product'
export {default as Products} from './Products'
export {default as Cart} from './Cart'